fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    wget: "git://github.com/maestrodev/puppet-wget.git"
    deploy: "git://github.com/mkrakowitzer/puppet-deploy.git"
  symlinks:
    crowd: "#{source_dir}"