fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    wget: "https://github.com/maestrodev/puppet-wget.git"
    deploy: "https://github.com/mkrakowitzer/puppet-deploy.git"
  symlinks:
    crowd: "#{source_dir}"
